# Instructions:

blueprint:
  name: IKEA SYMFONISK - Light Control (ZHA)
  description: Control light brightness, hue and color with an IKEA SYMFONISK dial

  domain: automation

  input:
    dial:
      name: Rotary dial
      description: Select the rotary dial you wish to use to control the values
      selector:
        device:
          filter:
            integration: zha
            model: SYMFONISK Sound Controller
            manufacturer: IKEA of Sweden

    rgb_toggle:
      name: RGB toggle
      description: An input boolean helper to store whether an RGB control mode is currently active
      selector:
        entity:
          filter:
            domain: input_boolean

    mode_tracker:
      name: Mode tracker
      description: An input number helper to store the current mode in (1-5)
      selector:
        entity:
          filter:
            domain: input_number

    color_tracker:
      name: Color tracker
      description: An input number helper to store the current RGB value in (0-1535)
      selector:
        entity:
          filter:
            domain: input_number

    color_code_tracker:
      name: Color code tracker
      description: An input text helper to store the current RGB color value in (255,255,0)
      selector:
        entity:
          filter:
            domain: input_text

    hue_tracker:
      name: Hue/Temperature tracker
      description: An input number helper to store the current hue/temperature in (2000-6500)
      selector:
        entity:
          filter:
            domain: input_number

    brightness_tracker:
      name: Brightness tracker
      description: An input number helper to store the current brightness in (0-255)
      selector:
        entity:
          filter:
            domain: input_number

# Queued, to ignore non-matched events but capture existing ones
mode: queued
max: 200
max_exceeded: silent

variables:
  dial: !input "dial"
  mode_tracker: !input "mode_tracker"
  hue_tracker: !input "hue_tracker"
  brightness_tracker: !input "brightness_tracker"
  color_tracker: !input "color_tracker"
  color_code_tracker: !input "color_code_tracker"
  rgb_toggle: !input "rgb_toggle"
  command: "{{ trigger.event.data.command }}"
  single_pressed: "{{ command == 'toggle' }}"
  # double_pressed: "{{ command == 'move_saturation' }}" # dumb: https://github.com/zigpy/zha-device-handlers/blob/92c9fbc6d01a5d86f78d64183302b906aa7d8215/zhaquirks/tuya/ts004f.py#L146C37-L146C37
  rotated: "{{ command == 'move' }}"
  positive: "{{ rotated and trigger.event.data.params.move_mode == 0 }}"
  step_size: > # Will always be 195
    {% if rotated %}
      {{ trigger.event.data.params.rate | float(0) }}
    {% else %}
      {{ 0 }}
    {% endif %}
  # How many steps to go full rotation (195 per step * 20 steps per full rotation)
  full_rotate_step_count: "{{ 195 * 20 | int }}"
  current_mode: "{{ states(mode_tracker) | int }}"
  min_mode: "{{ state_attr(mode_tracker, 'min') | int }}"
  max_mode: "{{ state_attr(mode_tracker, 'max') | int }}"
  # always increment, looping
  next_mode: >
    {% set val = current_mode + 1 %} 
    {% if val > max_mode %} 
      {% set val = min_mode %}
    {% endif %}
    {{ val | int }}
  current_rgb_toggle: "{{ states(rgb_toggle) == 'on' }}"
  min_hue: "{{ state_attr(hue_tracker, 'min') | int }}"
  max_hue: "{{ state_attr(hue_tracker, 'max') | int }}"
  # How many steps to go full min-max spectrum (2 full rotations)
  hue_steps: "{{ full_rotate_step_count * 2 | int }}"
  hue_delta: "{{ (step_size | float(0) / hue_steps) * (max_hue - min_hue) }}"
  # don't loop when reached max or min
  next_hue: >
    {%- set val = states(hue_tracker) | float(0) -%}
    {%- set delta = hue_delta -%}
    {%- if not positive -%}
      {%- set delta = delta * -1 -%}
    {%- endif -%}
    {%- set val = val + delta | int -%}
    {%- if positive and val > max_hue -%}
      {%- set val = max_hue -%}
    {%- elif not positive and val < min_hue -%}
      {%- set val = min_hue -%}
    {%- endif -%}
    {{ val | int }}
  min_brightness: "{{ state_attr(brightness_tracker, 'min') | int }}"
  max_brightness: "{{ state_attr(brightness_tracker, 'max') | int }}"
  # How many steps to go full min-max spectrum (2 full rotations)
  brightness_steps: "{{ full_rotate_step_count * 2 | int }}"
  brightness_delta: "{{ (step_size | float(0) / brightness_steps) * (max_brightness - min_brightness) }}"
  # don't loop when reached max or min
  next_brightness: >
    {%- set val = states(brightness_tracker) | float(0) -%}
    {%- set delta = brightness_delta -%}
    {%- if not positive -%}
      {%- set delta = delta * -1 -%}
    {%- endif -%}
    {%- set val = val + delta | int -%}
    {%- if positive and val > max_brightness -%} 
      {%- set val = max_brightness -%}
    {%- elif not positive and val < min_brightness -%}
      {%- set val = min_brightness -%}
    {%- endif -%}
    {{ val | int }}
  min_color: "{{ state_attr(color_tracker, 'min') | int }}"
  max_color: "{{ state_attr(color_tracker, 'max') | int }}"
  # How many steps to go full min-max spectrum (2 full rotations)
  color_steps: "{{ full_rotate_step_count * 3 | int }}"
  color_delta: "{{ (step_size | float(0) / color_steps) * (max_color - min_color) }}"
  # loop when reached max or min
  next_color: >
    {%- set val = states(color_tracker) | float(0) -%}
    {%- set delta = color_delta -%}
    {%- if not positive -%}
      {%- set delta = delta * -1 -%}
    {%- endif -%}
    {%- set val = val + delta | int -%}
    {%- if positive and val > max_color -%}
      {%- set val = val % max_color -%}
    {%- elif not positive and val < min_color -%}
      {%- set diff = min_color - val -%}
      {%- set val = max_color - (diff % max_color) -%}
    {%- endif -%}
    {{ val | int }}
  next_color_rgb_code: >
    {%- set r = 0 -%}
    {%- set g = 0 -%}
    {%- set b = 0 -%}

    {%- set index = next_color | int -%}

    {%- if index > 0 and index <= 256 -%}
      {%- set r = 255 -%}
      {%- set g = index -%}
      {%- set b = 0 -%}
    {%- elif index > 256 and index <= 512 -%}
      {%- set r = 512 - index -%}
      {%- set g = 255 -%}
      {%- set b = 0 -%}
    {%- elif index > 512 and index <= 768 -%}
      {%- set r = 0 -%}
      {%- set g = 255 -%}
      {%- set b = index - 512 -%}
    {%- elif index > 768 and index <= 1024 -%}
      {%- set r = 0 -%}
      {%- set g = 1024 - index -%}
      {%- set b = 255 -%}
    {%- elif index > 1024 and index <= 1280 -%}
      {%- set r = index - 1024 -%}
      {%- set g = 0 -%}
      {%- set b = 255 -%}
    {%- elif index > 1280 and index <= 1536 -%}
      {%- set r = 255 -%}
      {%- set g = 0 -%}
      {%- set b = 1536 - index -%}
    {%- endif -%}
    
    {%- set r = r | string -%}
    {%- set g = g | string -%}
    {%- set b = b | string -%}
    
    {{ r + "," + g + "," + b }}

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input dial

action:
  # Process current event
  - choose:
      # If event was a dial turn
      - conditions:
          - condition: template
            value_template: "{{ rotated }}"
            alias: Dial turned (0 for right, 1 for left)
        sequence:
          # Process different actions based on current mode
          - choose:
              # In Mode 1 (Power)
              - conditions:
                  - condition: template
                    value_template: "{{ current_mode == 1 }}"
                    alias: In Mode 1 (Power)
                sequence:
                  - service: input_boolean.turn_off
                    data: {}
                    target:
                      entity_id: !input rgb_toggle
                    alias: Disable RGB toggle
              # In Mode 2 (Temperature)
              - conditions:
                  - condition: template
                    value_template: "{{ current_mode == 2 }}"
                    alias: In Mode 2 (Temperature)
                sequence:
                  # Important to enable RGB toggle FIRST so it will be set in time for other triggered automations to check it
                  - service: input_boolean.turn_on
                    data: {}
                    target:
                      entity_id: !input rgb_toggle
                    alias: Enable RGB toggle
                  - service: input_number.set_value
                    entity_id: !input hue_tracker
                    data:
                      value: "{{ next_hue }}"
                    alias: Update hue/temperature tracker
              # In Mode 3 (Brightness)
              - conditions:
                  - condition: template
                    value_template: "{{ current_mode == 3 }}"
                    alias: In Mode 3 (Brightness)
                sequence:
                  # Important to enable RGB toggle FIRST so it will be set in time for other triggered automations to check it
                  - service: input_boolean.turn_on
                    data: {}
                    target:
                      entity_id: !input rgb_toggle
                    alias: Enable RGB toggle
                  - service: input_number.set_value
                    entity_id: !input brightness_tracker
                    data:
                      value: "{{ next_brightness }}"
                    alias: Update brightness tracker
              # In Mode 4 (Color)
              - conditions:
                  - condition: template
                    value_template: "{{ current_mode == 4 }}"
                    alias: In Mode 4 (Color)
                sequence:
                  # Important to enable RGB toggle FIRST so it will be set in time for other triggered automations to check it
                  - service: input_boolean.turn_on
                    data: {}
                    target:
                      entity_id: !input rgb_toggle
                    alias: Enable RGB toggle
                  - service: input_number.set_value
                    entity_id: !input color_tracker
                    data:
                      value: "{{ next_color }}"
                    alias: Update color tracker
                  - service: input_text.set_value
                    entity_id: !input color_code_tracker
                    data:
                      value: "{{ next_color_rgb_code }}"
                    alias: Update color code tracker
              # In Mode 5 (Brightness)
              - conditions:
                  - condition: template
                    value_template: "{{ current_mode == 5 }}"
                    alias: In Mode 5 (Brightness)
                sequence:
                  # Important to enable RGB toggle FIRST so it will be set in time for other triggered automations to check it
                  - service: input_boolean.turn_on
                    data: {}
                    target:
                      entity_id: !input rgb_toggle
                    alias: Enable RGB toggle
                  - service: input_number.set_value
                    entity_id: !input brightness_tracker
                    data:
                      value: "{{ next_brightness }}"
                    alias: Update brightness tracker
            alias: Determine action based on mode
      # If event was a dial button short push
      - conditions:
          - condition: template
            value_template: "{{ single_pressed }}"
        sequence:
          # Change mode (cycling back if reached the end)
          - service: input_number.set_value
            entity_id: !input mode_tracker
            data:
              value: "{{ next_mode }}"
            alias: Switch to next mode
          # Toggle RGB boolean based on mode
          - if:
              - condition: template
                value_template: "{{ next_mode == 1 }}"
                alias: Entering Mode 1 (Power)
            then:
              - service: input_boolean.turn_off
                data: {}
                target:
                  entity_id: !input rgb_toggle
            else:
              - service: input_boolean.turn_on
                data: {}
                target:
                  entity_id: !input rgb_toggle
